# Generated by Django 5.2.6 on 2025-09-09 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва правила')),
                ('rule_type', models.CharField(choices=[('income_threshold', 'Поріг доходу'), ('expense_category', 'Категорія витрат'), ('vat_exemption', 'ПДВ пільга'), ('esv_exemption', 'ЄСВ пільга')], max_length=20, verbose_name='Тип правила')),
                ('fop_group', models.CharField(choices=[('1', '1 група'), ('2', '2 група'), ('3', '3 група')], max_length=1, verbose_name='Група ФОП')),
                ('condition', models.JSONField(verbose_name='Умова')),
                ('action', models.JSONField(verbose_name='Дія')),
                ('priority', models.IntegerField(default=0, verbose_name='Пріоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило розрахунку податків',
                'verbose_name_plural': 'Правила розрахунку податків',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('monthly', 'Місячний'), ('quarterly', 'Квартальний'), ('yearly', 'Річний'), ('manual', 'Ручний')], max_length=20, verbose_name='Тип розрахунку')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Місяць')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Квартал')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Загальний дохід')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Загальні витрати')),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оподатковуваний дохід')),
                ('single_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Єдиний податок')),
                ('esv_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ЄСВ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ПДВ')),
                ('income_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Податок на доходи')),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Загальна сума податків')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('calculated', 'Розраховано'), ('approved', 'Затверджено'), ('paid', 'Сплачено')], default='draft', max_length=20, verbose_name='Статус')),
                ('calculation_data', models.JSONField(default=dict, verbose_name='Дані розрахунку')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='fop.fopprofile')),
            ],
            options={
                'verbose_name': 'Розрахунок податків',
                'verbose_name_plural': 'Розрахунки податків',
                'ordering': ['-year', '-month', '-quarter'],
                'unique_together': {('fop_profile', 'calculation_type', 'year', 'month', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemption_type', models.CharField(choices=[('vat', 'ПДВ'), ('esv', 'ЄСВ'), ('single_tax', 'Єдиний податок')], max_length=20, verbose_name='Тип пільги')),
                ('valid_from', models.DateField(verbose_name='Діє з')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Діє до')),
                ('exemption_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Відсоток пільги')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальна сума')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_exemptions', to='fop.fopprofile')),
            ],
            options={
                'verbose_name': 'Податкова пільга',
                'verbose_name_plural': 'Податкові пільги',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('single_tax', 'Єдиний податок'), ('esv', 'ЄСВ'), ('vat', 'ПДВ'), ('income_tax', 'Податок на доходи'), ('penalty', 'Штраф'), ('fine', 'Пеня')], max_length=20, verbose_name='Тип платежу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сплачена сума')),
                ('due_date', models.DateField(verbose_name='Термін сплати')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата сплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Референс платежу')),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID банківської транзакції')),
                ('payment_data', models.JSONField(default=dict, verbose_name='Дані платежу')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tax_calculations.taxcalculation')),
            ],
            options={
                'verbose_name': 'Платіж податку',
                'verbose_name_plural': 'Платежі податків',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('single_tax', 'Єдиний податок'), ('esv', 'ЄСВ'), ('vat', 'ПДВ'), ('income_tax', 'Податок на доходи')], max_length=20, verbose_name='Тип податку')),
                ('fop_group', models.CharField(choices=[('1', '1 група'), ('2', '2 група'), ('3', '3 група')], max_length=1, verbose_name='Група ФОП')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка (%)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Мінімальна сума')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальна сума')),
                ('valid_from', models.DateField(verbose_name='Діє з')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Діє до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Податкова ставка',
                'verbose_name_plural': 'Податкові ставки',
                'ordering': ['tax_type', 'fop_group', 'valid_from'],
                'unique_together': {('tax_type', 'fop_group', 'valid_from')},
            },
        ),
    ]
