# Generated by Django 5.2.6 on 2025-09-10 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва звіту')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('report_type', models.CharField(max_length=50, verbose_name='Тип звіту')),
                ('format', models.CharField(max_length=10, verbose_name='Формат')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('generating', 'Генерується'), ('ready', 'Готовий'), ('signed', 'Підписано'), ('submitted', 'Подано'), ('rejected', 'Відхилено'), ('error', 'Помилка')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Згенеровано')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Підписано')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Подано')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/generated/', verbose_name='Згенерований файл')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='reports/signed/', verbose_name='Підписаний файл')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метадані')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Повідомлення про помилку')),
                ('fop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fop.fopprofile', verbose_name='Профіль ФОП')),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fop.taxperiod', verbose_name='Податковий період')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('kep', 'Кваліфікований електронний підпис (КЕП)'), ('diia', 'Дія.Підпис'), ('bank_id', 'BankID'), ('other', 'Інший')], max_length=20, verbose_name='Тип підпису')),
                ('signer_name', models.CharField(max_length=200, verbose_name="Ім'я підписанта")),
                ('signer_identifier', models.CharField(max_length=100, verbose_name='Ідентифікатор підписанта')),
                ('certificate_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серійний номер сертифікату')),
                ('signature_file', models.FileField(upload_to='reports/signatures/', verbose_name='Файл підпису')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='reports/certificates/', verbose_name='Файл сертифікату')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Підписано')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Валідний')),
                ('validation_message', models.TextField(blank=True, null=True, verbose_name='Повідомлення валідації')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='reports.report', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Цифровий підпис',
                'verbose_name_plural': 'Цифрові підписи',
                'db_table': 'reports_signature',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Дані звіту')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reports.report', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Дані звіту',
                'verbose_name_plural': 'Дані звітів',
                'db_table': 'reports_data',
            },
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100, unique=True, verbose_name='ID подачі')),
                ('submission_url', models.URLField(blank=True, null=True, verbose_name='URL подачі')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('submitted', 'Подано'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено'), ('error', 'Помилка')], default='pending', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Подано')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Відповідь отримано')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Дані відповіді')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Повідомлення про помилку')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='reports.report', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Подача звіту',
                'verbose_name_plural': 'Подачі звітів',
                'db_table': 'reports_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва шаблону')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('report_type', models.CharField(choices=[('single_tax', 'Єдиний податок (ЄП)'), ('social_contribution', 'Єдиний соціальний внесок (ЄСВ)'), ('vat', 'Податок на додану вартість (ПДВ)'), ('income_tax', 'Податок на доходи фізичних осіб'), ('custom', 'Користувацький звіт')], max_length=50, verbose_name='Тип звіту')),
                ('format', models.CharField(choices=[('xml', 'XML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON')], default='xml', max_length=10, verbose_name='Формат')),
                ('template_content', models.TextField(verbose_name='Вміст шаблону')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/', verbose_name='Файл шаблону')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічний')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версія')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Шаблон звіту',
                'verbose_name_plural': 'Шаблони звітів',
                'db_table': 'reports_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttemplate', verbose_name='Шаблон'),
        ),
    ]
