# Generated by Django 5.2.6 on 2025-09-09 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('template_type', models.CharField(choices=[('tax_deadline', 'Дедлайн податку'), ('payment_reminder', 'Нагадування про платіж'), ('monthly_report', 'Місячний звіт'), ('weekly_report', 'Тижневий звіт'), ('system_alert', 'Системне сповіщення')], max_length=20, verbose_name='Тип шаблону')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('telegram', 'Telegram')], max_length=20, verbose_name='Канал')),
                ('subject_template', models.CharField(max_length=200, verbose_name='Шаблон теми')),
                ('body_template', models.TextField(verbose_name='Шаблон тіла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('variables', models.JSONField(default=list, verbose_name='Змінні шаблону')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон нотифікації',
                'verbose_name_plural': 'Шаблони нотифікацій',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Тіло')),
                ('channel', models.CharField(max_length=20, verbose_name='Канал')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('normal', 'Звичайний'), ('high', 'Високий'), ('urgent', 'Терміновий')], default='normal', max_length=10, verbose_name='Пріоритет')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('sent', 'Відправлено'), ('failed', 'Помилка'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('context_data', models.JSONField(default=dict, verbose_name='Контекстні дані')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Зовнішній ID')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заплановано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Відправлено о')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено о')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Кількість спроб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Нотифікація',
                'verbose_name_plural': 'Нотифікації',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Дія')),
                ('details', models.JSONField(default=dict, verbose_name='Деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Лог нотифікації',
                'verbose_name_plural': 'Логи нотифікацій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email увімкнено')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS увімкнено')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push увімкнено')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram увімкнено')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Початок тихих годин')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Кінець тихих годин')),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=50, verbose_name='Часовий пояс')),
                ('tax_deadline_enabled', models.BooleanField(default=True, verbose_name='Дедлайни податків')),
                ('payment_reminder_enabled', models.BooleanField(default=True, verbose_name='Нагадування про платежі')),
                ('report_enabled', models.BooleanField(default=True, verbose_name='Звіти')),
                ('system_alert_enabled', models.BooleanField(default=True, verbose_name='Системні сповіщення')),
                ('daily_digest', models.BooleanField(default=False, verbose_name='Щоденний дайджест')),
                ('weekly_digest', models.BooleanField(default=True, verbose_name='Тижневий дайджест')),
                ('monthly_digest', models.BooleanField(default=True, verbose_name='Місячний дайджест')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування нотифікацій',
                'verbose_name_plural': 'Налаштування нотифікацій',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at', 'status'], name='notificatio_schedul_963ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template', 'status'], name='notificatio_templat_1a9c31_idx'),
        ),
    ]
