# Generated by Django 5.2.6 on 2025-09-09 21:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва рахунку')),
                ('account_type', models.CharField(choices=[('checking', 'Розрахунковий'), ('savings', 'Депозитний'), ('credit', 'Кредитний'), ('investment', 'Інвестиційний')], max_length=20, verbose_name='Тип рахунку')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Назва банку')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Номер рахунку')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('category_type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата'), ('transfer', 'Переказ')], max_length=20, verbose_name='Тип категорії')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Колір')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Іконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['category_type', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва бюджету')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума')),
                ('period', models.CharField(choices=[('monthly', 'Щомісячний'), ('weekly', 'Тижневий'), ('yearly', 'Річний'), ('custom', 'Користувацький')], max_length=20, verbose_name='Період')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.category')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджети',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всього рядків')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Оброблено рядків')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Завдання імпорту',
                'verbose_name_plural': 'Завдання імпорту',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва правила')),
                ('rule_type', models.CharField(choices=[('description', 'За описом'), ('merchant', 'За мерчантом'), ('amount', 'За сумою'), ('account', 'За рахунком')], max_length=20, verbose_name='Тип правила')),
                ('condition', models.CharField(max_length=500, verbose_name='Умова')),
                ('priority', models.IntegerField(default=0, verbose_name='Пріоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума')),
                ('transaction_type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата'), ('transfer', 'Переказ')], max_length=20, verbose_name='Тип транзакції')),
                ('description', models.TextField(verbose_name='Опис')),
                ('merchant', models.CharField(blank=True, max_length=200, verbose_name='Мерчант')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Зовнішній ID')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'), models.Index(fields=['account', 'date'], name='finance_tra_account_588697_idx'), models.Index(fields=['category', 'date'], name='finance_tra_categor_e54d5a_idx')],
            },
        ),
    ]
