# Generated by Django 5.2.6 on 2025-09-09 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва банку')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код банку')),
                ('bank_type', models.CharField(choices=[('mono', 'Монобанк'), ('privat', 'ПриватБанк'), ('oschad', 'Ощадбанк'), ('raiffeisen', 'Райффайзен Банк'), ('ukrsib', 'УкрСиббанк')], max_length=20, verbose_name='Тип банку')),
                ('api_base_url', models.URLField(verbose_name='Базовий URL API')),
                ('auth_url', models.URLField(verbose_name='URL авторизації')),
                ('token_url', models.URLField(verbose_name='URL отримання токену')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL webhook')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(verbose_name='Redirect URI')),
                ('scope', models.TextField(default='read', verbose_name='Scope')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Sandbox режим')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='ID рахунку в банку')),
                ('account_number', models.CharField(max_length=29, verbose_name='Номер рахунку')),
                ('account_type', models.CharField(max_length=20, verbose_name='Тип рахунку')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Кредитний ліміт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Остання синхронізація')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank_integration.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Банківський рахунок',
                'verbose_name_plural': 'Банківські рахунки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bank', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='BankSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Ручна'), ('scheduled', 'За розкладом'), ('webhook', 'Webhook')], max_length=20, verbose_name='Тип синхронізації')),
                ('status', models.CharField(choices=[('started', 'Розпочато'), ('success', 'Успішно'), ('failed', 'Помилка'), ('partial', 'Частково')], max_length=20, verbose_name='Статус')),
                ('transactions_imported', models.IntegerField(default=0, verbose_name='Імпортовано транзакцій')),
                ('transactions_updated', models.IntegerField(default=0, verbose_name='Оновлено транзакцій')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Кількість помилок')),
                ('started_at', models.DateTimeField(verbose_name='Розпочато о')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено о')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Тривалість')),
                ('details', models.JSONField(default=dict, verbose_name='Деталі')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='bank_integration.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог синхронізації банку',
                'verbose_name_plural': 'Логи синхронізації банків',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BankWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('transaction', 'Нова транзакція'), ('balance', 'Зміна балансу'), ('account', 'Зміна рахунку'), ('error', 'Помилка')], max_length=20, verbose_name='Тип webhook')),
                ('payload', models.JSONField(verbose_name='Дані webhook')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='Підпис')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Оброблено о')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='bank_integration.bank')),
            ],
            options={
                'verbose_name': 'Банківський webhook',
                'verbose_name_plural': 'Банківські webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_type', models.CharField(default='Bearer', max_length=20, verbose_name='Тип токену')),
                ('expires_at', models.DateTimeField(verbose_name='Термін дії')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='bank_integration.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Банківський токен',
                'verbose_name_plural': 'Банківські токени',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bank')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в банку')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('transaction_type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата'), ('transfer', 'Переказ')], max_length=20, verbose_name='Тип транзакції')),
                ('description', models.TextField(verbose_name='Опис')),
                ('merchant', models.CharField(blank=True, max_length=255, verbose_name='Мерчант')),
                ('mcc_code', models.CharField(blank=True, max_length=4, verbose_name='MCC код')),
                ('transaction_date', models.DateTimeField(verbose_name='Дата транзакції')),
                ('processed_date', models.DateTimeField(verbose_name='Дата обробки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('is_categorized', models.BooleanField(default=False, verbose_name='Категоризовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='bank_integration.bankaccount')),
                ('internal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Банківська транзакція',
                'verbose_name_plural': 'Банківські транзакції',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['bank_account', 'transaction_date'], name='bank_integr_bank_ac_a9ccfd_idx'), models.Index(fields=['external_id'], name='bank_integr_externa_a4f947_idx'), models.Index(fields=['is_processed'], name='bank_integr_is_proc_24cba2_idx')],
                'unique_together': {('bank_account', 'external_id')},
            },
        ),
    ]
