# Generated by Django 5.2.6 on 2025-09-09 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('tax_number', models.CharField(max_length=10, unique=True, verbose_name='ІПН')),
                ('registration_date', models.DateField(verbose_name='Дата реєстрації')),
                ('tax_group', models.CharField(choices=[('1', '1 група - до 300 тис. грн'), ('2', '2 група - до 1.5 млн грн'), ('3', '3 група - до 7 млн грн')], max_length=1, verbose_name='Податкова група')),
                ('tax_system', models.CharField(choices=[('single', 'Єдиний податок'), ('general', 'Загальна система'), ('simplified', 'Спрощена система')], max_length=20, verbose_name='Система оподаткування')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Назва банку')),
                ('bank_code', models.CharField(max_length=10, verbose_name='МФО')),
                ('account_number', models.CharField(max_length=29, verbose_name='Номер рахунку')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fop_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль ФОП',
                'verbose_name_plural': 'Профілі ФОП',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FOPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_channels', models.JSONField(default=list, verbose_name='Канали нотифікацій')),
                ('notify_before_deadline', models.IntegerField(default=7, verbose_name='Сповіщати за днів до дедлайну')),
                ('notify_weekly', models.BooleanField(default=True, verbose_name='Тижневі звіти')),
                ('notify_monthly', models.BooleanField(default=True, verbose_name='Місячні звіти')),
                ('auto_calculate_tax', models.BooleanField(default=True, verbose_name='Автоматичний розрахунок податку')),
                ('include_vat', models.BooleanField(default=False, verbose_name='Включати ПДВ')),
                ('export_format', models.CharField(default='excel', max_length=10, verbose_name='Формат експорту')),
                ('include_receipts', models.BooleanField(default=True, verbose_name='Включати квитанції')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fop_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='fop.fopprofile')),
            ],
            options={
                'verbose_name': 'Налаштування ФОП',
                'verbose_name_plural': 'Налаштування ФОП',
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Місячний'), ('quarterly', 'Квартальний'), ('yearly', 'Річний')], max_length=20, verbose_name='Тип періоду')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Місяць')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Квартал')),
                ('declaration_deadline', models.DateField(verbose_name='Дедлайн подачі декларації')),
                ('payment_deadline', models.DateField(verbose_name='Дедлайн сплати')),
                ('declaration_submitted', models.BooleanField(default=False, verbose_name='Декларація подана')),
                ('payment_made', models.BooleanField(default=False, verbose_name='Сплачено')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сума податку')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сплачена сума')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_periods', to='fop.fopprofile')),
            ],
            options={
                'verbose_name': 'Податковий період',
                'verbose_name_plural': 'Податкові періоди',
                'ordering': ['-year', '-month', '-quarter'],
                'unique_together': {('fop_profile', 'period_type', 'year', 'month', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='TaxObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('single_tax', 'Єдиний податок'), ('esv', 'ЄСВ'), ('vat', 'ПДВ'), ('income_tax', 'Податок на доходи')], max_length=20, verbose_name="Тип зобов'язання")),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Розрахована сума')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сплачена сума')),
                ('payment_deadline', models.DateField(verbose_name='Дедлайн сплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('calculated', 'Розраховано'), ('paid', 'Сплачено'), ('overdue', 'Прострочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('calculation_data', models.JSONField(default=dict, verbose_name='Дані для розрахунку')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Референс платежу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_obligations', to='fop.fopprofile')),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='fop.taxperiod')),
            ],
            options={
                'verbose_name': "Податкове зобов'язання",
                'verbose_name_plural': "Податкові зобов'язання",
                'ordering': ['-created_at'],
            },
        ),
    ]
